[package]
name = "abr-home-system-benchmark"
version = "11.0.0"
edition = "2021"

[[bin]]
name = "benchmark"
path = "src/main.rs"

[[bin]]
name = "probe"
path = "src/probe.rs"

[lib]
name = "abr_home_system_benchmark"
path = "src/lib.rs"

[dependencies]

[[bin]]
name = "substrate"
path = "src/substrate_model.rs"
